# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#04020e\033\\"
printf "\033]4;1;#2d024a\033\\"
printf "\033]4;2;#53047e\033\\"
printf "\033]4;3;#2b1b60\033\\"
printf "\033]4;4;#45166e\033\\"
printf "\033]4;5;#4b1b69\033\\"
printf "\033]4;6;#473783\033\\"
printf "\033]4;7;#ba39d2\033\\"
printf "\033]4;8;#11083a\033\\"
printf "\033]4;9;#38025c\033\\"
printf "\033]4;10;#67059d\033\\"
printf "\033]4;11;#352178\033\\"
printf "\033]4;12;#561b89\033\\"
printf "\033]4;13;#5d2183\033\\"
printf "\033]4;14;#5844a3\033\\"
printf "\033]4;15;#f94cff\033\\"

# Background
printf "\033]11;#04020e\033\\";

# Foreground
printf "\033]10;#f94cff\033\\";

# Cursor
printf "\033]12;#f94cff\033\\";

# Border
printf "\033]7044;#f94cff\033\\";
