# Set term colors script - Generated by hellwal

# Colors from 0-15
printf "\033]4;0;#0e0a09\033\\"
printf "\033]4;1;#5d3432\033\\"
printf "\033]4;2;#674039\033\\"
printf "\033]4;3;#775238\033\\"
printf "\033]4;4;#895f57\033\\"
printf "\033]4;5;#9a5c56\033\\"
printf "\033]4;6;#8a7675\033\\"
printf "\033]4;7;#db9f8e\033\\"
printf "\033]4;8;#3d2b25\033\\"
printf "\033]4;9;#74413e\033\\"
printf "\033]4;10;#805047\033\\"
printf "\033]4;11;#946646\033\\"
printf "\033]4;12;#ab766c\033\\"
printf "\033]4;13;#c0736b\033\\"
printf "\033]4;14;#ac9392\033\\"
printf "\033]4;15;#ffd5be\033\\"

# Background
printf "\033]11;#0e0a09\033\\";

# Foreground
printf "\033]10;#ffd5be\033\\";

# Cursor
printf "\033]12;#ffd5be\033\\";

# Border
printf "\033]7044;#ffd5be\033\\";
