# Generated by hellwal

wallpaper='/home/nixlinco/Pictures/wallpaper/stat/wallhaven-zywe5j.jpg'

background='0e0a09'
foreground='ffd5be'
cursor='ffd5be'
border='ffd5be'

color0='0e0a09'
color1='5d3432'
color2='674039'
color3='775238'
color4='895f57'
color5='9a5c56'
color6='8a7675'
color7='db9f8e'
color8='3d2b25'
color9='74413e'
color10='805047'
color11='946646'
color12='ab766c'
color13='c0736b'
color14='ac9392'
color15='ffd5be'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
