# Generated by hellwal

wallpaper='/home/nixlinco/Pictures/wallpaper/stat/wallhaven-l8x1pr.jpg'

background='04020e'
foreground='f94cff'
cursor='f94cff'
border='f94cff'

color0='04020e'
color1='2d024a'
color2='53047e'
color3='2b1b60'
color4='45166e'
color5='4b1b69'
color6='473783'
color7='ba39d2'
color8='11083a'
color9='38025c'
color10='67059d'
color11='352178'
color12='561b89'
color13='5d2183'
color14='5844a3'
color15='f94cff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
